name: "📚 Docs"
description: "문서 작업 시 작성해주세요"
title: "Docs: "
labels: ["documentation"]
body:
  - type: textarea
    id: docs-description
    attributes:
      label: 📝 문서 작업 내용
      description: 어떤 문서 작업을 하는지 설명해주세요.
      placeholder: README.md 업데이트, API 명세서 작성 등
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: ✅ 작업 상세 내용
      description: 문서 작업의 세부 내용을 작성해주세요.
      placeholder: |
        - [ ] TODO 1
        - [ ] TODO 2
      value: |
        - [ ] 
    validations:
      required: true
